server {
    listen 4321;
    server_name localhost;

    root /home/tomycat/code/blogs/dist;
    index index.html;

    location /_astro/ {
        expires 1y;
        add_header Cache-Control "public, immutable";
        access_log off;
    }

    location /fonts/ {
        expires 1y;
        add_header Cache-Control "public, immutable";
        access_log off;
    }

    location /favicon {
        expires 30d;
        access_log off;
    }

    location / {
        try_files $uri $uri/ $uri.html /404.html;
    }
}

    location /fonts/ {
        expires 1y;
        add_header Cache-Control "public, immutable";
        access_log off;
    }

    location /favicon {
        expires 30d;
        access_log off;
    }

    location / {
        try_files $uri $uri/ $uri.html /404.html;
    }
}
